### ISSUE TITLE
Cannot convert PDF to MXL

### ISSUE THREAD

**Issue by Tobertet** [weidi/audiveris-docker#6]
Hi, I am trying to convert a pdf to a mxl. However, I'm receiving the following error. Does anyone know what is happening and how can I solve it? The PDF is super basic, it's a C major scale written with lilypond.

```
########################################################


INFO  [test]            StepMonitoring 96   | MEASURES
INFO  [test]                      Page 279  | 2 raw measures: [2 in system#1]
INFO  [test]            StepMonitoring 96   | CHORDS
INFO  [test]            StepMonitoring 96   | CURVES
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7c1bc8cca0, pid=1, tid=45
#
# JRE version: OpenJDK Runtime Environment (11.0.13+8) (build 11.0.13+8-alpine-r0)
# Java VM: OpenJDK 64-Bit Server VM (11.0.13+8-alpine-r0, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [ld-musl-x86_64.so.1+0x23ca0]
```

**Comment by weidi** [comment]
forget to push the most recent build that is now based on debian as i was unable to get alpine running. Please pull new image and try again.

**Comment by Tobertet** [comment]
Hi @weidi. With the latest image I managed to convert my PDF to musicXML, thank you. However, it looks like it is not formed correctly. 

For example, when I run the command `musicxml2ly` I get
`xml.parsers.expat.ExpatError: unbound prefix: line 76, column 10`

If I try to open it using MuseScore it says 
`File '/lilypond/output/test/test.mxl' is not a valid MusicXML file`

Since it is compressed I don't know how to fix it. Is there a way to create the musicxml uncompressed?

**Comment by weidi** [comment]
Hi Robert,

i´m just building that image but i´m not too deep into musicxml, you might
raise this question in the audiveris repository.

BR
Johannes

Am Di., 15. Feb. 2022 um 11:14 Uhr schrieb Robert Mengual <
***@***.***>:

**Comment by Tobertet** [comment]
Alright, thank you.
